CREATE SYNONYM syn_pengarang FOR pengarang;
CREATE SYNONYM anggota_syn FOR anggota;
CREATE SYNONYM buku_syn FOR buku;
CREATE SYNONYM pegawai_syn FOR pegawai;
CREATE SYNONYM peminjaman_syn FOR peminjaman;
CREATE SYNONYM pengunjung_syn FOR pengunjung;


SELECT * FROM ALL_SYNONYMS WHERE TABLE_NAME LIKE 'BUKU' OR TABLE_NAME LIKE 'ANGGOTA' OR TABLE_NAME LIKE 'PEGAWAI' OR TABLE_NAME LIKE 'PEMINJAMAN' OR TABLE_NAME LIKE 'PENGUNJUNG';